#!/bin/bash
#UpgradeTo=disco

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

if [ -f /usr/share/feren-os/majorupdate-force ]; then
    echo "${red}WARNING: You are running Feren OS Major Update in Force Update Mode, which prevents blocks put in by the Developer from stopping the update from occuring. This is EXTREMELY dangerous.${reset}"
    sleep 10
fi

while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done

echo "Checking if Packages aren't broken first, and fixing if so."
dpkg --configure -a --force-confdef --force-confold
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ]; then
	echo "[INFO] No Major Update Progress file found, assuming this is a freshly done Major Update..."
	apt-get -f install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y
	brokenpkgs=$(dpkg-query -f '${status} ${package}\n' -W | awk '$3 == "half-configured" {print $4}')
	borkedpkgnames=""
	for i in "$brokenpkgs"; do
		if [ "$borkedpkgnames" = "" ]; then
		        borkedpkgnames="$i"
	        else
		        borkedpkgnames="$borkedpkgnames $i"
		fi
	done
	if [ "$borkedpkgnames" = "acpid" ]; then
	        successful=true
	fi
	apt-get -f install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y
	if [[ $? -eq 0 ]] || [ $successful = true ]; then
		echo -en "\rChecking package situation will allow for a Major Update to commence... ${green}[ OK ]${reset}
	"
	else
		echo -en "\rChecking package situation will allow for a Major Update to commence... ${red}[ FAIL ]${reset}
	"
		echo "

	${red}Oops, your Feren OS installation is currently in broken package situation meaning that the Major Update will not be possible at this current moment in time without risking the breakage of core Feren OS packages. Please fix this issue and then reboot and try again.${reset}
	"
		echo "ENTER- Dismiss and continue booting"
		read
		systemctl -i reboot
		exit 0
	fi
else
	echo "[INFO] Major Update Progress file found, resuming from last checkpoint..."
fi
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
dpkg --configure -a --force-confdef --force-confold

echo -en "\rChecking that the Major Update process hasn't been blocked by the Developer... [...]" 
if [ -f /tmp/feren-majorupdate-blockmsg ]; then
    rm -f /tmp/feren-majorupdate-blockmsg
fi
wget -q --tries=10 --timeout=20 --spider https://gitlab.com/Feren-OS/Base-Upgrade-Scripts/raw/blockers/majorupdate-block
if [[ ! $? -eq 0 ]]; then
        echo -en "\rChecking that the Major Update process hasn't been blocked by the Developer... ${green}[ OK ]${reset}
"
        if [ -f /usr/share/feren-os/majorupdate-blocked-before ]; then
            rm -f /usr/share/feren-os/majorupdate-blocked-before
        fi
else
        wget https://gitlab.com/Feren-OS/Base-Upgrade-Scripts/raw/blockers/majorupdate-block -O /tmp/feren-majorupdate-blockmsg
        clear
        echo -en "\rChecking that the Major Update process hasn't been blocked by the Developer... ${red}[ FAIL ]${reset}
"
        if [ ! -f /usr/share/feren-os/majorupdate-force ]; then
            echo "

    ${red}Unfortunately, the Developer has blocked Major Updates from being installed by anyone. This could be due to a major issue regarding update paths or other major issues with the process that need to be fixed. Here's his reason for blocking major updates at this time:${reset}
    $(cat /tmp/feren-majorupdate-blockmsg)
    "
            echo "ENTER- Dismiss and continue booting"
            if [ ! -f /usr/share/feren-os/majorupdate-blocked-before ]; then
                touch /usr/share/feren-os/majorupdate-blocked-before
            fi
            read
            systemctl -i reboot
            exit 0
        fi
fi

# The Real Upgrade Process Begins
echo "Refreshing Package Sources..."
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
apt-get update
echo "Making sure the current system packages are up to date..."
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
apt-get install -y mint-common --reinstall
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
apt-get upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes
i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ]; then
	echo "ChkPoint1" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 1 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint1" ]; then
	apt-get -f install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	apt-get upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint1" ]; then
	echo "ChkPoint2" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 2 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint2" ]; then
	echo "Disabling Non-Feren-OS PPAs..."
	cd /etc/apt/sources.list.d
	for file in *.list; do
	    sed -e 's/^/#/' -i "$file"
	    sed -i 's/cosmic/disco/g' "$file"
	    newname=$(echo $file | sed "s/-cosmic.list/-disco.list/g")
	    mv "$file" "$newname"
	done
	echo "Re-adding Non-Feren-OS PPAs..."
	/var/lib/dpkg/info/feren-ppas.postinst --force-add-all
	echo "Done Adding PPAs!"
	echo "Ok, now that's done, let's get down to business. Firstly, let's switch the official repositories..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint2" ]; then
	echo "ChkPoint3" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 3 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint3" ]; then
	echo "deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse
	deb http://archive.ubuntu.com/ubuntu disco-updates main restricted universe multiverse
	deb http://archive.ubuntu.com/ubuntu disco-backports main restricted universe multiverse

	deb http://security.ubuntu.com/ubuntu/ disco-security main restricted universe multiverse
	deb http://archive.canonical.com/ubuntu/ disco partner" > /etc/apt/sources.list
	echo "deb http://packages.linuxmint.com tessa main import backport" > /etc/apt/sources.list.d/official-package-repositories.list
	echo "deb https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable main software" > /etc/apt/sources.list.d/feren-os.list
    echo "deb [trusted=yes] https://github.com/feren-OS/Feren-Repository-nonlts/raw/master ./" > /etc/apt/sources.list.d/feren-os-nonlts.list
    wget https://gitlab.com/feren-os/feren-repositories/raw/master/repositories/pool/main/f/feren-repository-keyring/feren-repository-keyring_2019.03.0.0.0_all.deb
    dpkg -i feren-repository-keyring_*.deb
    rm -f feren-repository-keyring_*.deb

	sed -i 's/18/19/g' /etc/lsb-release
	sed -i 's/19.3/19/g' /etc/lsb-release
	sed -i 's/19.2/19/g' /etc/lsb-release
	sed -i 's/19.1/19/g' /etc/lsb-release
	sed -i 's/18.10/19.04/g' /etc/lsb-release
	sed -i 's/tara/tessa/g' /etc/lsb-release
	sed -i 's/sarah/tessa/g' /etc/lsb-release
	sed -i 's/sonya/tessa/g' /etc/lsb-release
	sed -i 's/serena/tessa/g' /etc/lsb-release
	sed -i 's/sylvia/tessa/g' /etc/lsb-release
	sed -i 's/bionic/cosmic/g' /etc/lsb-release
	sed -i 's/cosmic/disco/g' /etc/lsb-release
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint3" ]; then
	echo "ChkPoint4" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 4 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint4" ]; then
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	apt-get update
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint4" ]; then
	echo "ChkPoint5" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 5 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint5" ]; then
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get -f install -y'

	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint5" ]; then
	echo "ChkPoint6" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 6 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint6" ]; then
	sh -c 'apt-get purge python3-aptdaemon.pkcompat gnome-user-share vino -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y'
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y'

	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint6" ]; then
	echo "ChkPoint7" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 7 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint7" ]; then
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	sh -c 'apt-get purge python3-aptdaemon.pkcompat gnome-user-share vino -y'
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get -f install -y'
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y'
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get -f install -y'
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y'
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get -f install -y'
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	sh -c 'apt-get purge python3-aptdaemon.pkcompat gnome-user-share vino -y'
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint7" ]; then
	echo "ChkPoint8" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 8 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint8" ]; then
	sh -c 'apt-get -f install -y'
	brokenpkgs=$(dpkg-query -f '${status} ${package}\n' -W | awk '$3 == "half-configured" {print $4}')
	borkedpkgnames=""
	for i in "$brokenpkgs"; do
	    if [ "$borkedpkgnames" = "" ]; then
		borkedpkgnames="$i"
	    else
		borkedpkgnames="$borkedpkgnames $i"
	    fi
	done
	if [ "$borkedpkgnames" = "acpid" ]; then
	    #ACPID will fail until we specify to have it installed very late in the script, so...
	    successful1=true
	fi
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
	sh -c 'apt-get -f install -y'
	dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	i=0
	tput sc
	while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
	    case $(($i % 4)) in
		0 ) j="-" ;;
		1 ) j="\\" ;;
		2 ) j="|" ;;
		3 ) j="/" ;;
	    esac
	    tput rc
	    echo -en "\r[$j] Waiting for other software managers to finish..." 
	    sleep 0.5
	    ((i=i+1))
	done
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint8" ]; then
	echo "ChkPoint9" > /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint
	echo "Checkpoint 9 Reached. If the Major Updater gets turned off prematurely, it'll be resumed from here..."
fi
if [ ! -f /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint ] || [ "$(cat /usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint)" = "ChkPoint9" ]; then
	apt-get -f install -y
    dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
	if [[ $? -eq 0 ]] || [ "$successful1" = true ]; then
		echo -en "\rChecking Update was successful... ${green}[ OK ]${reset}
	"
		if [ ! "$1" = "--shutdown" ]; then
		    echo "

	${green}System Update Completed Successfully! Performing last tasks and then Restarting...${reset}
	"
		else
		    echo "

	${green}System Update Completed Successfully! Performing last tasks and then Shutting Down...${reset}
	"
		fi
	else
		echo -en "\rChecking Update was successful... ${red}[ FAIL ]${reset}
	"
		echo "

	${red}Oops, looks like an error occured during the update, we'll try to rectify this, and then shut down.${reset}
	"
		i=0
		tput sc
		while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
		    case $(($i % 4)) in
		        0 ) j="-" ;;
		        1 ) j="\\" ;;
		        2 ) j="|" ;;
		        3 ) j="/" ;;
		    esac
		    tput rc
		    echo -en "\r[$j] Waiting for other software managers to finish..." 
		    sleep 0.5
		    ((i=i+1))
		done
		dpkg --configure -a
		tries=0
		successful=false
		while [ $tries -lt 100 ] && [ $successful = false ]; do
		    i=0
		    tput sc
		    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
		        case $(($i % 4)) in
		            0 ) j="-" ;;
		            1 ) j="\\" ;;
		            2 ) j="|" ;;
		            3 ) j="/" ;;
		        esac
		        tput rc
		        echo -en "\r[$j] Waiting for other software managers to finish..." 
		        sleep 0.5
		        ((i=i+1))
		    done
		    sh -c 'apt-get -f install -y'
		    dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
		    i=0
		    tput sc
		    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
		        case $(($i % 4)) in
		            0 ) j="-" ;;
		            1 ) j="\\" ;;
		            2 ) j="|" ;;
		            3 ) j="/" ;;
		        esac
		        tput rc
		        echo -en "\r[$j] Waiting for other software managers to finish..." 
		        sleep 0.5
		        ((i=i+1))
		    done
		    sh -c 'apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y'
		    i=0
		    tput sc
		    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
		        case $(($i % 4)) in
		            0 ) j="-" ;;
		            1 ) j="\\" ;;
		            2 ) j="|" ;;
		            3 ) j="/" ;;
		        esac
		        tput rc
		        echo -en "\r[$j] Waiting for other software managers to finish..." 
		        sleep 0.5
		        ((i=i+1))
		    done
		    sh -c 'apt-get -f install -y'
		    i=0
		    tput sc
		    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
		        case $(($i % 4)) in
		            0 ) j="-" ;;
		            1 ) j="\\" ;;
		            2 ) j="|" ;;
		            3 ) j="/" ;;
		        esac
		        tput rc
		        echo -en "\r[$j] Waiting for other software managers to finish..." 
		        sleep 0.5
		        ((i=i+1))
		    done
		    dpkg --purge --force-all plasma-look-and-feel-org-kde-breezedark-desktop
		    sh -c 'apt-get -f install -y'      
		    if [ $? -eq 0 ]; then
		        successful=true
		    else
		        successful=false
		    fi
		    brokenpkgs=$(dpkg-query -f '${status} ${package}\n' -W | awk '$3 == "half-configured" {print $4}')
		    borkedpkgnames=""
		    for i in "$brokenpkgs"; do
		        if [ "$borkedpkgnames" = "" ]; then
		            borkedpkgnames="$i"
		        else
		            borkedpkgnames="$borkedpkgnames $i"
		        fi
		    done
		    if [ "$borkedpkgnames" = "acpid" ]; then
		        #ACPID will fail until we specify to have it installed very late in the script, so...
		        successful=true
		    fi
		    tries=$((tries+1))
		done
		if [ $successful = true ]; then
		    echo "

	System Update Error Fix + Overall Update Completed Successfully! Doing last tasks...
	"
		else
		    echo "

	Sadly, the System Update Error Fix + Overall Update Failed. Attempting last tasks, and then you'll have to try to sort out the problems yourself...
	"
		fi
	fi
	#Begin Theme Recompilation
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' chromeos-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/chromeos-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' macos-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/macos-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' macosx-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/macosx-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' ubuntu-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/ubuntu-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' windows7-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/windows7-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' windows8-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/windows8-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' windows10-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/windows10-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' windowsvista-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/windowsvista-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' windowsxp-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/windowsxp-theme.postinst
	fi
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' yosembiance-theme|grep "install ok installed")
	if [ ! "" == "$PKG_OK" ]; then
		/var/lib/dpkg/info/yosembiance-theme.postinst
	fi
	#End Theme Recompilation
	systemctl disable feren-majorupdate
	rm -f /etc/systemd/system/feren-majorupdate.service
	systemctl disable feren-majorupdate-autoreboot
	rm -f /etc/systemd/system/feren-majorupdate-autoreboot.service
	systemctl enable feren-majorupdate-fix
	/usr/bin/feren-majorupdate-warning --remove-warning
	rm -f /usr/bin/feren-majorupdate-bootup /usr/bin/feren-majorupdate-upgrade /usr/bin/feren-majorupdate-session /usr/bin/feren-majorupdate-autoreboot feren-majorupdate-autoreboot /usr/bin/feren-majorupdate-schedule /usr/bin/feren-majorupdate-warning
	rm -rf /usr/share/feren-os-majorupdate/autostart-app
	echo "Removing Checkpoint now the Major Update is finished..."
	rm -f '/usr/share/feren-os-majorupdate/majorupdate-progress-checkpoint'
	apt-get -f install -y
	apt-get install ferensources-ubuntu feren-ppas feren-app-packages -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes
	if [ -f /usr/share/feren-os-majorupdate/cinnamon-installed ]; then
		apt-get -y install cinnamon
		echo "Making some last changes to fix issues arisen from Feren OS's new-ish package structure..."
		apt-get -y install feren-themer-cinnamon feren-config
		killall install-themer-layouts-cinnamon
		install-themer-layouts-cinnamon
	fi
	echo "We're done. Ubuntu 18.10 base has been updated to 19.04."
	rm -f /usr/bin/feren-majorupdate-upgrade
	rm -f /usr/share/feren-os-majorupdate/cinnamon-installed
	echo "disco" > /etc/feren-os-base
	exit 0
fi